<?xml version="1.0" encoding="utf-8"?><Database Name="StateInfo" Class="StateInformationDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\StateInfo.mdf;Integrated Security=True" SettingsObjectName="BFritsche206Lab3.Properties.Settings" SettingsPropertyName="StateInfoConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.StateInfo" Member="StateInfos">
    <Type Name="StateInfo">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="StateName" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="StatePopulation" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FlagDesc" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="StateFlower" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="StateBird" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Colors" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="FirstLargestCity" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="SecondLargestCity" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="ThirdLargestCity" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Capital" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="MedianIncome" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="ComputerJobPercentage" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>