#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BFritsche206Lab3
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="StateInfo")]
	public partial class StateInformationDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertStateInfo(StateInfo instance);
    partial void UpdateStateInfo(StateInfo instance);
    partial void DeleteStateInfo(StateInfo instance);
    #endregion
		
		public StateInformationDataContext() : 
				base(global::BFritsche206Lab3.Properties.Settings.Default.StateInfoConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public StateInformationDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public StateInformationDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public StateInformationDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public StateInformationDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<StateInfo> StateInfos
		{
			get
			{
				return this.GetTable<StateInfo>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.StateInfo")]
	public partial class StateInfo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _StateName;
		
		private int _StatePopulation;
		
		private string _FlagDesc;
		
		private string _StateFlower;
		
		private string _StateBird;
		
		private string _Colors;
		
		private string _FirstLargestCity;
		
		private string _SecondLargestCity;
		
		private string _ThirdLargestCity;
		
		private string _Capital;
		
		private decimal _MedianIncome;
		
		private decimal _ComputerJobPercentage;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnStateNameChanging(string value);
    partial void OnStateNameChanged();
    partial void OnStatePopulationChanging(int value);
    partial void OnStatePopulationChanged();
    partial void OnFlagDescChanging(string value);
    partial void OnFlagDescChanged();
    partial void OnStateFlowerChanging(string value);
    partial void OnStateFlowerChanged();
    partial void OnStateBirdChanging(string value);
    partial void OnStateBirdChanged();
    partial void OnColorsChanging(string value);
    partial void OnColorsChanged();
    partial void OnFirstLargestCityChanging(string value);
    partial void OnFirstLargestCityChanged();
    partial void OnSecondLargestCityChanging(string value);
    partial void OnSecondLargestCityChanged();
    partial void OnThirdLargestCityChanging(string value);
    partial void OnThirdLargestCityChanged();
    partial void OnCapitalChanging(string value);
    partial void OnCapitalChanged();
    partial void OnMedianIncomeChanging(decimal value);
    partial void OnMedianIncomeChanged();
    partial void OnComputerJobPercentageChanging(decimal value);
    partial void OnComputerJobPercentageChanged();
    #endregion
		
		public StateInfo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StateName", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string StateName
		{
			get
			{
				return this._StateName;
			}
			set
			{
				if ((this._StateName != value))
				{
					this.OnStateNameChanging(value);
					this.SendPropertyChanging();
					this._StateName = value;
					this.SendPropertyChanged("StateName");
					this.OnStateNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StatePopulation", DbType="Int NOT NULL")]
		public int StatePopulation
		{
			get
			{
				return this._StatePopulation;
			}
			set
			{
				if ((this._StatePopulation != value))
				{
					this.OnStatePopulationChanging(value);
					this.SendPropertyChanging();
					this._StatePopulation = value;
					this.SendPropertyChanged("StatePopulation");
					this.OnStatePopulationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FlagDesc", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string FlagDesc
		{
			get
			{
				return this._FlagDesc;
			}
			set
			{
				if ((this._FlagDesc != value))
				{
					this.OnFlagDescChanging(value);
					this.SendPropertyChanging();
					this._FlagDesc = value;
					this.SendPropertyChanged("FlagDesc");
					this.OnFlagDescChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StateFlower", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string StateFlower
		{
			get
			{
				return this._StateFlower;
			}
			set
			{
				if ((this._StateFlower != value))
				{
					this.OnStateFlowerChanging(value);
					this.SendPropertyChanging();
					this._StateFlower = value;
					this.SendPropertyChanged("StateFlower");
					this.OnStateFlowerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StateBird", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string StateBird
		{
			get
			{
				return this._StateBird;
			}
			set
			{
				if ((this._StateBird != value))
				{
					this.OnStateBirdChanging(value);
					this.SendPropertyChanging();
					this._StateBird = value;
					this.SendPropertyChanged("StateBird");
					this.OnStateBirdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Colors", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Colors
		{
			get
			{
				return this._Colors;
			}
			set
			{
				if ((this._Colors != value))
				{
					this.OnColorsChanging(value);
					this.SendPropertyChanging();
					this._Colors = value;
					this.SendPropertyChanged("Colors");
					this.OnColorsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstLargestCity", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string FirstLargestCity
		{
			get
			{
				return this._FirstLargestCity;
			}
			set
			{
				if ((this._FirstLargestCity != value))
				{
					this.OnFirstLargestCityChanging(value);
					this.SendPropertyChanging();
					this._FirstLargestCity = value;
					this.SendPropertyChanged("FirstLargestCity");
					this.OnFirstLargestCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SecondLargestCity", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string SecondLargestCity
		{
			get
			{
				return this._SecondLargestCity;
			}
			set
			{
				if ((this._SecondLargestCity != value))
				{
					this.OnSecondLargestCityChanging(value);
					this.SendPropertyChanging();
					this._SecondLargestCity = value;
					this.SendPropertyChanged("SecondLargestCity");
					this.OnSecondLargestCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThirdLargestCity", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string ThirdLargestCity
		{
			get
			{
				return this._ThirdLargestCity;
			}
			set
			{
				if ((this._ThirdLargestCity != value))
				{
					this.OnThirdLargestCityChanging(value);
					this.SendPropertyChanging();
					this._ThirdLargestCity = value;
					this.SendPropertyChanged("ThirdLargestCity");
					this.OnThirdLargestCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Capital", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Capital
		{
			get
			{
				return this._Capital;
			}
			set
			{
				if ((this._Capital != value))
				{
					this.OnCapitalChanging(value);
					this.SendPropertyChanging();
					this._Capital = value;
					this.SendPropertyChanged("Capital");
					this.OnCapitalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MedianIncome", DbType="Money NOT NULL")]
		public decimal MedianIncome
		{
			get
			{
				return this._MedianIncome;
			}
			set
			{
				if ((this._MedianIncome != value))
				{
					this.OnMedianIncomeChanging(value);
					this.SendPropertyChanging();
					this._MedianIncome = value;
					this.SendPropertyChanged("MedianIncome");
					this.OnMedianIncomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ComputerJobPercentage", DbType="Decimal(18,0) NOT NULL")]
		public decimal ComputerJobPercentage
		{
			get
			{
				return this._ComputerJobPercentage;
			}
			set
			{
				if ((this._ComputerJobPercentage != value))
				{
					this.OnComputerJobPercentageChanging(value);
					this.SendPropertyChanging();
					this._ComputerJobPercentage = value;
					this.SendPropertyChanged("ComputerJobPercentage");
					this.OnComputerJobPercentageChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
